### PR TITLE
Upgrade Pylint to 2.16.2

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

- Updates the minimum Pylint version to 2.16.2 following Terra's PR https://github.com/Qiskit/qiskit-terra/pull/9615
- Updates pylintrc file and github action workflow using #431
- Applies black to setup.py

Co-authored-by: Manoel Marques <Manoel.Marques@ibm.com>

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
A general comment here. For the apps, given its a lot less code, we used to lint on the latest version as well as whatever Terra used. Yes when it changed it might affect/break CI. I am not fan of fixing a specific version, and linting against something that may be older, but it is a tradeoff I agree. Will we end up updating it or forget it. Already pylint is at 2.17.1. Given the apps are not as active now maybe its something we have to do or need to do

**Comment by t-imamichi** [comment]
I copied the removal of the latest lint from #431. It makes sense to me to apply the same pylint version as Terra because applying the latest pylint version has a risk to break CI suddenly due to breaking change of pylint.

**Comment by woodsp-ibm** [comment]
As far as I recall the app repos were set to lint using the same of lint as Terra as well as the new version. Its a tradeoff as I mentioned - I did not like being "stuck" on some on older version and not taking advantage of any new features/capability that might help with code quality, hence we did both. Yes it sometimes fails due to new checks that were not done before. For #431 the older versions did not work and hence Manoel had to remove that

**Comment by t-imamichi** [comment]
As for mypy, we always apply the latest one because we don't pin mypy as follows.
As for pylint, it might be enough to set `pylint>=2.16.2` and apply only the latest one in the CI.
https://github.com/Qiskit/qiskit-optimization/blob/8044ee0e74c7560908d30328dfcaf430a7ad4bf6/requirements-dev.txt#L17

**Comment by t-imamichi** [comment]
I updated requirements-dev.txt to apply the latest pylint at CI 5d7f3e4. It looks working.

**Comment by woodsp-ibm** [comment]
Ok, my rational to suggest pinning them and having another job running on the latest which was not required to pass CI and hence would not block things if it failed was more a response to this

>the latest pylint version has a risk to break CI suddenly

We have usually just done emergency fixes to sort things, for both this and mypy since that can break CI if/when new rules  come in. Anyway its something we can consider going forwards i.e. have main CI running on pinned versions we know work, and an extra job testing against latest versions such that we can fix things more leisurely if they break.

**Comment by woodsp-ibm** [comment]
Ok, my rational to suggest pinning them and having another job running on the latest which was not required to pass CI and hence would not block things if it failed was more a response to this

>the latest pylint version has a risk to break CI suddenly

We have usually just done emergency fixes to sort things, for both this and mypy since that can break CI if/when new rules  come in. Anyway its something we can consider going forwards i.e. have main CI running on pinned versions we know work, and an extra job testing against latest versions such that we can fix things more leisurely if they break.

**Review by woodsp-ibm — APPROVED** [review]
I must admit the extra brackets in the tests, for me improved readability and more clearly signaled the intent.

**Comment by t-imamichi** [comment]
Thanks. Since the current CI tests with the latest pylint, this PR does not increase the risk of CI breakage. Let's discuss pinning pylint version if necessary.

**Pull request merged**
