### PR TITLE
Turn off CI for forks

### PR DESCRIPTION
**Pull request by Eric-Arellano**
Most people agree that GitHub made a mistake by having forks run CI both on the fork and in the upstream repository. It wastes computing resources (which has a real environmental cost!).

If people really want to run CI in their fork, they can always modify their fork's config to revert this change.

### CODE REVIEW

**Review by t-imamichi — APPROVED** [review]
LGTM. Thanks.

**Comment by Eric-Arellano** [comment]
Thanks for the review! I don't have write access, if you could please hit merge.

**Comment by Eric-Arellano** [comment]
Github still is dealing with an outage: https://www.githubstatus.com

**Comment by woodsp-ibm** [comment]
@t-imamichi I responded back - the mergify.yml file needs updating - the job it used to check success was the 3.7 version which you changed to 3.8 so that now needs to be the 3.8 one (two places in that file)

**Comment by t-imamichi** [comment]
Thank you, @woodsp-ibm. I have merged #507.

**Pull request merged**
