### PR TITLE
Increase tutorials timeout

### PR DESCRIPTION
**Pull request by manoelmarques**

### CODE REVIEW

**Review by woodsp-ibm — APPROVED** [review]
Tutorials were supposed to be quick running - hopefully this does not in general lead to longer running tutorials.

**Comment by t-imamichi** [comment]
Oh, I didn't notice this issue. Which tutorial takes so long time?

**Comment by t-imamichi** [comment]
I see admm tutorial failed. I'm wondering why it happens suddenly. I will take a look at recent terra changes.

https://github.com/Qiskit/qiskit-optimization/runs/4382590459?check_suite_focus=true
```
Notebook error:
CellTimeoutError in tutorials/05_admm_optimizer.ipynb:
A cell timed out while it was being executed, after 180 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
# run ADMM to solve problem
result_q = admm_q.solve(qp)
-------------------
```

**Comment by t-imamichi** [comment]
I found out the root cause. https://github.com/Qiskit/qiskit-terra/issues/7337

**Pull request merged**
